[2024-02-10T16:04:06.957+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_weather_data.send_email_task manual__2024-02-10T16:03:55.979467+00:00 [queued]>
[2024-02-10T16:04:06.972+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_weather_data.send_email_task manual__2024-02-10T16:03:55.979467+00:00 [queued]>
[2024-02-10T16:04:06.973+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2024-02-10T16:04:06.996+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): send_email_task> on 2024-02-10 16:03:55.979467+00:00
[2024-02-10T16:04:07.003+0000] {standard_task_runner.py:60} INFO - Started process 119 to run task
[2024-02-10T16:04:07.007+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_weather_data', 'send_email_task', 'manual__2024-02-10T16:03:55.979467+00:00', '--job-id', '40', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp4q4k9uw7']
[2024-02-10T16:04:07.012+0000] {standard_task_runner.py:88} INFO - Job 40: Subtask send_email_task
[2024-02-10T16:04:07.079+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_weather_data.send_email_task manual__2024-02-10T16:03:55.979467+00:00 [running]> on host 0d632e0d618d
[2024-02-10T16:04:07.578+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Lucas Andrini' AIRFLOW_CTX_DAG_ID='etl_weather_data' AIRFLOW_CTX_TASK_ID='send_email_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-10T16:03:55.979467+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-10T16:03:55.979467+00:00'
[2024-02-10T16:04:07.590+0000] {etl_dag.py:187} INFO - Tipo de datos temp: float64
[2024-02-10T16:04:07.591+0000] {etl_dag.py:191} INFO - min temp: 5.0
[2024-02-10T16:04:07.592+0000] {etl_dag.py:194} INFO - max temp: 30.0
[2024-02-10T16:04:07.604+0000] {warnings.py:109} WARNING - /opt/***/dags/etl_dag.py:202: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rows_to_notify.loc[df_transformed['temp'] < min_temperature, 'limite'] = min_temperature

[2024-02-10T16:04:07.610+0000] {etl_dag.py:208} INFO - Filas a notificar:
[2024-02-10T16:04:07.611+0000] {etl_dag.py:209} INFO -   country                                          name  temp  limite
1      GS  South Georgia and the South Sandwich Islands  2.57     5.0
[2024-02-10T16:04:07.647+0000] {etl_dag.py:235} INFO - mail: None
[2024-02-10T16:04:07.649+0000] {etl_dag.py:236} INFO - msg: Content-Type: multipart/mixed; boundary="===============7750837728442580796=="
MIME-Version: 1.0
Subject: Alerta de temperatura

--===============7750837728442580796==
Content-Type: text/html; charset="utf-8"
MIME-Version: 1.0
Content-Transfer-Encoding: base64

RmVjaGEgZGUgZW52w61vOiAyMDI0LTAyLTEwIDE2OjA0OjA3Cgo8dGFibGUgYm9yZGVyPSIxIiBj
bGFzcz0iZGF0YWZyYW1lIj4KICA8dGhlYWQ+CiAgICA8dHIgc3R5bGU9InRleHQtYWxpZ246IHJp
Z2h0OyI+CiAgICAgIDx0aD5jb3VudHJ5PC90aD4KICAgICAgPHRoPm5hbWU8L3RoPgogICAgICA8
dGg+dGVtcDwvdGg+CiAgICAgIDx0aD5saW1pdGU8L3RoPgogICAgPC90cj4KICA8L3RoZWFkPgog
IDx0Ym9keT4KICAgIDx0cj4KICAgICAgPHRkPkdTPC90ZD4KICAgICAgPHRkPlNvdXRoIEdlb3Jn
aWEgYW5kIHRoZSBTb3V0aCBTYW5kd2ljaCBJc2xhbmRzPC90ZD4KICAgICAgPHRkPjIuNTc8L3Rk
PgogICAgICA8dGQ+NS4wPC90ZD4KICAgIDwvdHI+CiAgPC90Ym9keT4KPC90YWJsZT4=

--===============7750837728442580796==--

[2024-02-10T16:04:08.961+0000] {etl_dag.py:248} ERROR - 'NoneType' object has no attribute 'encode'
[2024-02-10T16:04:08.963+0000] {etl_dag.py:249} ERROR - Error al enviar el correo electrÃ³nico.
[2024-02-10T16:04:08.965+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-10T16:04:08.983+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_weather_data, task_id=send_email_task, execution_date=20240210T160355, start_date=20240210T160406, end_date=20240210T160408
[2024-02-10T16:04:09.029+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-10T16:04:09.206+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
