[2024-02-10T23:37:35.520+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_weather_data.send_email_task manual__2024-02-10T23:37:16.992025+00:00 [queued]>
[2024-02-10T23:37:35.537+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_weather_data.send_email_task manual__2024-02-10T23:37:16.992025+00:00 [queued]>
[2024-02-10T23:37:35.538+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 2
[2024-02-10T23:37:35.570+0000] {taskinstance.py:2192} INFO - Executing <Task(PythonOperator): send_email_task> on 2024-02-10 23:37:16.992025+00:00
[2024-02-10T23:37:35.579+0000] {standard_task_runner.py:60} INFO - Started process 86 to run task
[2024-02-10T23:37:35.585+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'etl_weather_data', 'send_email_task', 'manual__2024-02-10T23:37:16.992025+00:00', '--job-id', '38', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp_jfkas2d']
[2024-02-10T23:37:35.591+0000] {standard_task_runner.py:88} INFO - Job 38: Subtask send_email_task
[2024-02-10T23:37:35.678+0000] {task_command.py:423} INFO - Running <TaskInstance: etl_weather_data.send_email_task manual__2024-02-10T23:37:16.992025+00:00 [running]> on host 3ebc09df1e7c
[2024-02-10T23:37:36.153+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Lucas Andrini' AIRFLOW_CTX_DAG_ID='etl_weather_data' AIRFLOW_CTX_TASK_ID='send_email_task' AIRFLOW_CTX_EXECUTION_DATE='2024-02-10T23:37:16.992025+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-02-10T23:37:16.992025+00:00'
[2024-02-10T23:37:36.164+0000] {etl_dag.py:184} INFO - Tipo de datos temp: float64
[2024-02-10T23:37:36.165+0000] {etl_dag.py:188} INFO - min temp: 5.0
[2024-02-10T23:37:36.165+0000] {etl_dag.py:191} INFO - max temp: 30.0
[2024-02-10T23:37:36.177+0000] {warnings.py:109} WARNING - /opt/***/dags/etl_dag.py:199: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  rows_to_notify.loc[df_transformed['temp'] < min_temperature, 'limite'] = min_temperature

[2024-02-10T23:37:36.181+0000] {etl_dag.py:205} INFO - Filas a notificar:
[2024-02-10T23:37:36.182+0000] {etl_dag.py:206} INFO -   country                                          name   temp  limite
1      GS  South Georgia and the South Sandwich Islands   2.49     5.0
3     NaN                                           NaN   0.40     5.0
4     NaN                                           NaN -33.91     5.0
5     NaN                                           NaN   0.07     5.0
[2024-02-10T23:37:39.564+0000] {etl_dag.py:239} INFO - Correo electrónico enviado con éxito.
[2024-02-10T23:37:39.566+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-02-10T23:37:39.584+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=etl_weather_data, task_id=send_email_task, execution_date=20240210T233716, start_date=20240210T233735, end_date=20240210T233739
[2024-02-10T23:37:39.661+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-02-10T23:37:39.708+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
